// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_rH3kHhtMndkTHrVha2z_EPIb27Usggg',
    appId: '1:9691196237:web:68af014117e41812986504',
    messagingSenderId: '9691196237',
    projectId: 'shoppestore-b1181',
    authDomain: 'shoppestore-b1181.firebaseapp.com',
    storageBucket: 'shoppestore-b1181.appspot.com',
    measurementId: 'G-7YRC3MYKL9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9RXoR5DgGrfMY8jJi3oczyYCL85DNcXY',
    appId: '1:9691196237:android:bb094e7e4994aa2e986504',
    messagingSenderId: '9691196237',
    projectId: 'shoppestore-b1181',
    storageBucket: 'shoppestore-b1181.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnfv3clvK9Pw16EeG8p_fa25OHvP67Tpw',
    appId: '1:9691196237:ios:3760355171d0dc63986504',
    messagingSenderId: '9691196237',
    projectId: 'shoppestore-b1181',
    storageBucket: 'shoppestore-b1181.appspot.com',
    iosBundleId: 'com.example.shoppeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnfv3clvK9Pw16EeG8p_fa25OHvP67Tpw',
    appId: '1:9691196237:ios:3760355171d0dc63986504',
    messagingSenderId: '9691196237',
    projectId: 'shoppestore-b1181',
    storageBucket: 'shoppestore-b1181.appspot.com',
    iosBundleId: 'com.example.shoppeapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_rH3kHhtMndkTHrVha2z_EPIb27Usggg',
    appId: '1:9691196237:web:70b99cf04de1059c986504',
    messagingSenderId: '9691196237',
    projectId: 'shoppestore-b1181',
    authDomain: 'shoppestore-b1181.firebaseapp.com',
    storageBucket: 'shoppestore-b1181.appspot.com',
    measurementId: 'G-CPGNS3617H',
  );
}
